_wandb:
    value:
        cli_version: 0.22.2
        e:
            b1xo02t0inhlnj5p5dc7plvvylnijki0:
                codePath: cifar_exp/main.py
                codePathLocal: cifar_exp/main.py
                cpu_count: 24
                cpu_count_logical: 32
                disk:
                    /:
                        total: "1967281065984"
                        used: "1167450279936"
                email: robert.vdklis@protonmail.com
                executable: /local/home/rvander/hyperbolic-fully-connected/.venv/bin/python3
                git:
                    commit: 578d435a6f01958a54799fd25460b79d340f6ae4
                    remote: git@github.com:robertdvdk/hyperbolic-fully-connected.git
                host: rvander-pc.inf.ethz.ch
                memory:
                    total: "67090022400"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.39
                program: /local/home/rvander/hyperbolic-fully-connected/cifar_exp/main.py
                python: CPython 3.13.11
                root: /local/home/rvander/hyperbolic-fully-connected
                startedAt: "2026-03-24T16:50:46.230781Z"
                writerId: b1xo02t0inhlnj5p5dc7plvvylnijki0
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.13.11
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 128
checkpoint_dir:
    value: ./checkpoints
compile:
    value: false
curvature:
    value: 1
data_split_seed:
    value: 42
early_stopping:
    value: false
early_stopping_patience:
    value: 10
embedding_dim:
    value: null
evaluate_test:
    value: false
fc_variant:
    value: ours
hidden_dim:
    value: 64
init_method:
    value: xavier
input_proj_type:
    value: conv_bn_relu
learning_rate:
    value: 0.1
lorentz_method:
    value: theirs
lr_decay:
    value: 0.2
manifold:
    value: lorentz
mlr_init:
    value: mlr
mlr_type:
    value: fc_mlr
momentum:
    value: 0.9
norm_config:
    value: normal_noweightnorm
normalisation_mode:
    value: centering_only
num_epochs:
    value: 200
optimizer:
    value: sgd
resume_checkpoint:
    value: null
scheduler:
    value: steplr
seed:
    value: 0
train_subset_fraction:
    value: 1
use_weight_norm:
    value: true
val_fraction:
    value: 0.1
warmup_epochs:
    value: 0
weight_decay:
    value: 0.0005
